"""claim leases

Revision ID: b21c553586bf
Revises: 70f2dcb3e6f2
Create Date: 2026-10-06 15:54:33.489883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b21c553586bf'
down_revision: Union[str, Sequence[str], None] = '70f2dcb3e6f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitors', sa.Column('lease_token', sa.String(length=36), nullable=True))
    op.add_column('monitors', sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('notifications', sa.Column('claim_token', sa.String(length=36), nullable=True))
    op.add_column('notifications', sa.Column('claimed_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'claimed_until')
    op.drop_column('notifications', 'claim_token')
    op.drop_column('monitors', 'lease_expires_at')
    op.drop_column('monitors', 'lease_token')
    # ### end Alembic commands ###
